version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001

  frontend:
    build:
      context: ./view
      dockerfile: Dockerfile
    ports:
      - 3000:3000 